/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    stakeholder: Stakeholder;
    itinerari: Itinerari;
    documenti: Documenti;
    attivita: Attivita;
    luoghi: Luoghi;
    news: News;
    residenze: Residenze;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  Keywords?: string | null;
  Tipologia?: string | null;
  Nome: string;
  Data_Produzione?: string | null;
  URL_Esterno?: string | null;
  Credits?: string | null;
  Descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stakeholder".
 */
export interface Stakeholder {
  id: string;
  Nome: string;
  Descrizione?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  Tipologia?: ('Azienda' | 'Ristoratori' | 'etc') | null;
  Itinerario?: (string | null) | Itinerari;
  media?: (string | Media)[] | null;
  contatti?:
    | {
        contatto?: string | null;
        'info-contatto'?: string | null;
        id?: string | null;
      }[]
    | null;
  'Link Esterni'?:
    | {
        'Nome-link'?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itinerari".
 */
export interface Itinerari {
  id: string;
  nome?: string | null;
  'descrizione-itinerario'?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  Luoghi?: (string | Luoghi)[] | null;
  Punti?:
    | {
        /**
         * @minItems 2
         * @maxItems 2
         */
        Punti?: [number, number] | null;
        Luoghi?: (string | Luoghi)[] | null;
        id?: string | null;
      }[]
    | null;
  'Media-Localizzati'?:
    | {
        /**
         * @minItems 2
         * @maxItems 2
         */
        'punto-media'?: [number, number] | null;
        media?: (string | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  'mappa-gpx'?: string | Media | null;
  'link-prenotazione-guida'?: string | null;
  media?: (string | Media)[] | null;
  'info-itinerario'?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lunghezza?: string | null;
  tempo?: string | null;
  dislivello?: string | null;
  Tipo?: ('tipo-0' | 'tipo-1' | 'tipo-2')[] | null;
  Difficoltà?: ('facile' | 'media' | 'difficile') | null;
  'servizi-aggiuntivi-integrati'?:
    | {
        servizio?: string | null;
        'url-prenotazione'?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "luoghi".
 */
export interface Luoghi {
  id: string;
  nome: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  posizione?: [number, number] | null;
  'attività-servizi'?:
    | {
        attivià?: string | null;
        'info-attività'?: string | null;
        id?: string | null;
      }[]
    | null;
  media?: (string | null) | Media;
  'info-contatti'?:
    | {
        contatto?: string | null;
        info?: string | null;
        id?: string | null;
      }[]
    | null;
  descrizione?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documenti".
 */
export interface Documenti {
  id: string;
  Nome: string;
  Descrizione?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  Autore?:
    | {
        nome?: string | null;
        cognome?: string | null;
        id?: string | null;
      }[]
    | null;
  Data?: string | null;
  Tipo?: string | null;
  links?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  media?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attivita".
 */
export interface Attivita {
  id: string;
  Nome: string;
  Descrizione?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  Organizzatori?:
    | {
        Nome?: string | null;
        Ruolo?: string | null;
        id?: string | null;
      }[]
    | null;
  Luogo?: (string | null) | Luoghi;
  Data_Inizio?: string | null;
  Data_Fine?: string | null;
  Tipo?: string | null;
  Prenotazione_Necessaria?: boolean | null;
  Itinerario?: (string | null) | Itinerari;
  media?: (string | Media)[] | null;
  Output_Documenti?: (string | null) | Documenti;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  Titolo: string;
  Programma?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  'Data-pubblicazione'?: string | null;
  Media?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residenze".
 */
export interface Residenze {
  id: string;
  Nome: string;
  abstract?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  programma?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  'tutore-ed-esperti'?:
    | {
        nome?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  'data-inizio'?: string | null;
  'data-fine'?: string | null;
  'figure-richieste'?:
    | {
        figura?: string | null;
        'descrizione-figura'?: string | null;
        id?: string | null;
      }[]
    | null;
  'link-iscrizione'?: string | null;
  deadline?: string | null;
  media?: (string | null) | Media;
  'descrizione-processo'?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  'descrizione-output'?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  'link-esterni'?:
    | {
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  documenti?:
    | {
        file?: string | Media | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}